### ISSUE TITLE
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters

### ISSUE THREAD

**Issue by pegasusmail** [mergebase/log4j-detector#10]
-- Examining /usr/share/ca-certificates/mozilla/AC_RAIZ_FNMT-RCM.crt...
Exception in thread "main" java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /usr/share/ca-certificates/mozilla/AC_Ra??z_Certic??mara_S.A..crt
        at java.base/sun.nio.fs.UnixPath.encode(UnixPath.java:145)
        at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
        at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:280)
        at java.base/java.io.File.toPath(File.java:2290)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:322)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:333)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:333)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:333)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:333)
        at com.mergebase.log4j.Log4JDetector.main(Log4JDetector.java:72)

**Comment by pegasusmail** [comment]
-- Examining /home/tuser/downloads/mobility/demo/images/Thumbs.db...
Exception in thread "main" java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /home/tuser/downloads/mobility/demo/p??dagogische Akademie
        at java.base/sun.nio.fs.UnixPath.encode(UnixPath.java:145)
        at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
        at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:280)
        at java.base/java.io.File.toPath(File.java:2290)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:322)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:333)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:333)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:333)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:333)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:333)
        at com.mergebase.log4j.Log4JDetector.main(Log4JDetector.java:72)

**Comment by pegasusmail** [comment]
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

Description:    Debian GNU/Linux 8.11 (jessie)

log4j-detector-2021.12.13.jar

**Comment by tempelmann** [comment]
Same here:

```
# java -jar log4j-detector-2021.12.13.jar /usr > out.txt
Exception in thread "main" java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /usr/share/ca-certificates/mozilla/NetLock_Arany_=Class_Gold=_F??tan??s??tv??ny.crt
	at java.base/sun.nio.fs.UnixPath.encode(UnixPath.java:145)
	at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
	at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279)
	at java.base/java.io.File.toPath(File.java:2329)
	at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:341)
	at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:352)
	at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:352)
	at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:352)
	at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:352)
	at com.mergebase.log4j.Log4JDetector.main(Log4JDetector.java:72)
```

**Comment by juliusmusseau** [comment]
Should be fixed now!  (latest version - just pushed)
