### ISSUE TITLE
scanning /dev folder on (NAS) unix causes program to freeze

### ISSUE THREAD

**Issue by Feathered-Serpent** [mergebase/log4j-detector#14]
I tried running the detector on my Synology NAS via putty.

on my first try it just... basically freezes after reaching a certain folder structure (running as root for / (root) directory):
```
-- Examining /.old_patch_info/.system_info/bits...
-- Examining /.old_patch_info/.system_info/endian...
-- Examining /.old_patch_info/.system_info/pgsql_alignment...
-- Examining /.old_patch_info/.system_info/Sone.5...
-- Examining /.old_patch_info/synoinfo.conf...
-- Examining /.old_patch_info/VERSION...
-- Examining /.rnd...
-- Examining /.syno/dsminfo/default_config.log...
-- Examining /.syno/dsminfo/VERSION.init...
-- Examining /.syno/patch/bios.ROM...
-- Examining /.syno/patch/checksum.syno...
-- Examining /.syno/patch/grub_cksum.syno...
-- Examining /.syno/patch/GRUB_VER...
-- Examining /.syno/patch/H2OFFT-Lx64...
-- Examining /.syno/patch/platform.ini...
-- Examining /.syno/patch/rd.gz...
-- Examining /.syno/patch/SynoBootLoader.conf...
-- Examining /.syno/patch/updater...
-- Examining /.syno/patch/VERSION...
-- Examining /.syno/patch/zImage...
-- Examining /.system_info/bits...
-- Examining /.system_info/endian...
-- Examining /.system_info/pgsql_alignment...
-- Examining /.system_info/Sone.5...
-- Examining /config/pool/cache_info...
-- Examining /config/pool/ext_jnl_cache_cnt...
-- Examining /config/pool/ext_jnl_enable...
-- Examining /config/pool/ext_jnl_path...
-- Examining /config/pool/ext_jnl_suspend...
-- Examining /config/pool/help...
-- Examining /config/pool/preread_control...
-- Examining /config/rodsys/help...
-- Examining /config/rodsys/local_key...
-- Examining /config/rodsys/throttle_interval_msec...
-- Examining /config/target/core/alua/lu_gps/default_lu_gp/lu_gp_id...
-- Examining /config/target/core/alua/lu_gps/default_lu_gp/members...
-- Examining /config/target/core/epio_0/hba_info...
-- Examining /config/target/core/epio_0/hba_mode...
-- Examining /config/target/core/epio_0/odx_info...
-- Examining /config/target/core/epio_0/odx_mode...
-- Examining /config/target/core/epio_1/hba_info...
-- Examining /config/target/core/epio_1/hba_mode...
-- Examining /config/target/core/epio_1/odx_info...
-- Examining /config/target/core/epio_1/odx_mode...
-- Examining /config/target/core/fileio_0/hba_info...
-- Examining /config/target/core/fileio_0/hba_mode...
-- Examining /config/target/core/fileio_0/odx_info...
-- Examining /config/target/core/fileio_0/odx_mode...
-- Examining /config/target/core/iblock_0/hba_info...
-- Examining /config/target/core/iblock_0/hba_mode...
-- Examining /config/target/core/iblock_0/odx_info...
-- Examining /config/target/core/iblock_0/odx_mode...
-- Examining /config/target/core/multifile_0/hba_info...
-- Examining /config/target/core/multifile_0/hba_mode...
-- Examining /config/target/core/multifile_0/odx_info...
-- Examining /config/target/core/multifile_0/odx_mode...
-- Examining /config/target/dbroot...
-- Examining /config/target/io_delay_msec...
-- Examining /config/target/io_delay_per_io...
-- Examining /config/target/iscsi/discovery_auth/authenticate_target...
-- Examining /config/target/iscsi/discovery_auth/enforce_discovery_auth...
-- Examining /config/target/iscsi/discovery_auth/password...
-- Examining /config/target/iscsi/discovery_auth/password_mutual...
-- Examining /config/target/iscsi/discovery_auth/userid...
-- Examining /config/target/iscsi/discovery_auth/userid_mutual...
-- Examining /config/target/iscsi/global_np_enable...
-- Examining /config/target/iscsi/lio_version...
-- Examining /config/target/loopback/version...
-- Examining /config/target/version...
-- Examining /config/vsys/help...
-- Examining /dev/bus/usb/001/001...
-- Examining /dev/bus/usb/001/002...
-- Examining /dev/bus/usb/002/001...
-- Examining /dev/bus/usb/003/001...
-- Examining /dev/bus/usb/004/001...
```

Ctrl+C'ed the program after two hours. After not running it as root (and thus not 'reaching' those structures) it first causes an OoM when trying to access /dev/full and, after raising the memory, freezes at /dev/null afterwards and doing nothing again.

**Comment by juliusmusseau** [comment]
Probably we need to add an "ignore" control (to ignore /dev).  On my machine scanning "/dev" does this, but appears that's not the case for you.  :-(

```
-- Skipping /dev/full - Not a regular file.
-- Skipping /dev/fuse - Not a regular file.
-- Skipping /dev/kmsg - Not a regular file.
-- Skipping /dev/kvm - Not a regular file.
-- Skipping /dev/net/tun - Not a regular file.
-- Skipping /dev/null - Not a regular file.
-- Skipping /dev/ptmx - Not a regular file.

```
Do you happen to know the sha1 of the log4j-detector-2021.12.13.jar file you used?

**Comment by Feathered-Serpent** [comment]
the sha1 of the downloaded file is 0ee90d8f10117e9485cca09dc9aa1b2d991ce01e

Maybe a Synology NAS also somehow works different and eventually the OS is stopping some accesses? But I only can guess that.

**Comment by Feathered-Serpent** [comment]
btw the log with Xmx4g:
```
java -Xmx4g -jar log4j-detector-2021.12.13.jar / --verbose
-- Analyzing paths (could take a long time).
-- Note: specify the '--verbose' flag to have every file examined printed to STDERR.
-- Examining /.old_patch_info/.system_info/bits...
-- Examining /.old_patch_info/.system_info/endian...
-- Examining /.old_patch_info/.system_info/pgsql_alignment...
-- Examining /.old_patch_info/synoinfo.conf...
-- Examining /.old_patch_info/VERSION...
-- Examining /.syno/dsminfo/default_config.log...
-- Examining /.syno/dsminfo/VERSION.init...
-- Examining /.syno/patch/bios.ROM...
-- Examining /.syno/patch/checksum.syno...
-- Examining /.syno/patch/grub_cksum.syno...
-- Examining /.syno/patch/GRUB_VER...
-- Examining /.syno/patch/H2OFFT-Lx64...
-- Examining /.syno/patch/platform.ini...
-- Examining /.syno/patch/rd.gz...
-- Examining /.syno/patch/SynoBootLoader.conf...
-- Examining /.syno/patch/updater...
-- Examining /.syno/patch/VERSION...
-- Examining /.syno/patch/zImage...
-- Examining /.system_info/bits...
-- Examining /.system_info/endian...
-- Examining /.system_info/pgsql_alignment...
-- Examining /config/pool/cache_info...
-- Examining /config/pool/ext_jnl_cache_cnt...
-- Examining /config/pool/ext_jnl_enable...
-- Examining /config/pool/ext_jnl_path...
-- Examining /config/pool/ext_jnl_suspend...
-- Examining /config/pool/help...
-- Examining /config/pool/preread_control...
-- Examining /config/rodsys/help...
-- Examining /config/rodsys/local_key...
-- Examining /config/rodsys/throttle_interval_msec...
-- Examining /config/target/core/alua/lu_gps/default_lu_gp/lu_gp_id...
-- Examining /config/target/core/alua/lu_gps/default_lu_gp/members...
-- Examining /config/target/core/epio_0/hba_info...
-- Examining /config/target/core/epio_0/hba_mode...
-- Examining /config/target/core/epio_0/odx_info...
-- Examining /config/target/core/epio_0/odx_mode...
-- Examining /config/target/core/epio_1/hba_info...
-- Examining /config/target/core/epio_1/hba_mode...
-- Examining /config/target/core/epio_1/odx_info...
-- Examining /config/target/core/epio_1/odx_mode...
-- Examining /config/target/core/fileio_0/hba_info...
-- Examining /config/target/core/fileio_0/hba_mode...
-- Examining /config/target/core/fileio_0/odx_info...
-- Examining /config/target/core/fileio_0/odx_mode...
-- Examining /config/target/core/iblock_0/hba_info...
-- Examining /config/target/core/iblock_0/hba_mode...
-- Examining /config/target/core/iblock_0/odx_info...
-- Examining /config/target/core/iblock_0/odx_mode...
-- Examining /config/target/core/multifile_0/hba_info...
-- Examining /config/target/core/multifile_0/hba_mode...
-- Examining /config/target/core/multifile_0/odx_info...
-- Examining /config/target/core/multifile_0/odx_mode...
-- Examining /config/target/dbroot...
-- Examining /config/target/io_delay_msec...
-- Examining /config/target/io_delay_per_io...
-- Problem: /config/target/iscsi/discovery_auth/authenticate_target - java.lang.RuntimeException: java.io.IOException: Operation not permitted
-- Examining /config/target/iscsi/discovery_auth/enforce_discovery_auth...
-- Problem: /config/target/iscsi/discovery_auth/password - java.lang.RuntimeException: java.io.IOException: Operation not permitted
-- Problem: /config/target/iscsi/discovery_auth/password_mutual - java.lang.RuntimeException: java.io.IOException: Operation not permitted
-- Problem: /config/target/iscsi/discovery_auth/userid - java.lang.RuntimeException: java.io.IOException: Operation not permitted
-- Problem: /config/target/iscsi/discovery_auth/userid_mutual - java.lang.RuntimeException: java.io.IOException: Operation not permitted
-- Examining /config/target/iscsi/global_np_enable...
-- Examining /config/target/iscsi/lio_version...
-- Examining /config/target/loopback/version...
-- Examining /config/target/version...
-- Examining /config/vsys/help...
-- Examining /dev/full...
/dev/full FAILED: java.lang.NegativeArraySizeException
java.lang.NegativeArraySizeException
        at com.mergebase.log4j.Bytes.resizeArray(Bytes.java:93)
        at com.mergebase.log4j.Bytes.streamToBytes(Bytes.java:56)
        at com.mergebase.log4j.Bytes.streamToBytes(Bytes.java:43)
        at com.mergebase.log4j.Bytes.streamToBytes(Bytes.java:39)
        at com.mergebase.log4j.Log4JDetector.findLog4jRecursive(Log4JDetector.java:257)
        at com.mergebase.log4j.Log4JDetector.scan(Log4JDetector.java:312)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:337)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:333)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:333)
        at com.mergebase.log4j.Log4JDetector.main(Log4JDetector.java:72)
-- Problem: /dev/fuse - java.lang.RuntimeException: java.io.IOException: Operation not permitted
-- Examining /dev/hda...
/dev/hda FAILED: java.lang.NegativeArraySizeException
java.lang.NegativeArraySizeException
        at com.mergebase.log4j.Bytes.resizeArray(Bytes.java:93)
        at com.mergebase.log4j.Bytes.streamToBytes(Bytes.java:56)
        at com.mergebase.log4j.Bytes.streamToBytes(Bytes.java:43)
        at com.mergebase.log4j.Bytes.streamToBytes(Bytes.java:39)
        at com.mergebase.log4j.Log4JDetector.findLog4jRecursive(Log4JDetector.java:257)
        at com.mergebase.log4j.Log4JDetector.scan(Log4JDetector.java:312)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:337)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:333)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:333)
        at com.mergebase.log4j.Log4JDetector.main(Log4JDetector.java:72)
-- Examining /dev/hda1...
/dev/hda1 FAILED: java.lang.NegativeArraySizeException
java.lang.NegativeArraySizeException
        at com.mergebase.log4j.Bytes.resizeArray(Bytes.java:93)
        at com.mergebase.log4j.Bytes.streamToBytes(Bytes.java:56)
        at com.mergebase.log4j.Bytes.streamToBytes(Bytes.java:43)
        at com.mergebase.log4j.Bytes.streamToBytes(Bytes.java:39)
        at com.mergebase.log4j.Log4JDetector.findLog4jRecursive(Log4JDetector.java:257)
        at com.mergebase.log4j.Log4JDetector.scan(Log4JDetector.java:312)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:337)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:333)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:333)
        at com.mergebase.log4j.Log4JDetector.main(Log4JDetector.java:72)
-- Examining /dev/hda2...
/dev/hda2 FAILED: java.lang.NegativeArraySizeException
java.lang.NegativeArraySizeException
        at com.mergebase.log4j.Bytes.resizeArray(Bytes.java:93)
        at com.mergebase.log4j.Bytes.streamToBytes(Bytes.java:56)
        at com.mergebase.log4j.Bytes.streamToBytes(Bytes.java:43)
        at com.mergebase.log4j.Bytes.streamToBytes(Bytes.java:39)
        at com.mergebase.log4j.Log4JDetector.findLog4jRecursive(Log4JDetector.java:257)
        at com.mergebase.log4j.Log4JDetector.scan(Log4JDetector.java:312)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:337)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:333)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:333)
        at com.mergebase.log4j.Log4JDetector.main(Log4JDetector.java:72)
-- Examining /dev/hda3...
/dev/hda3 FAILED: java.lang.NegativeArraySizeException
java.lang.NegativeArraySizeException
        at com.mergebase.log4j.Bytes.resizeArray(Bytes.java:93)
        at com.mergebase.log4j.Bytes.streamToBytes(Bytes.java:56)
        at com.mergebase.log4j.Bytes.streamToBytes(Bytes.java:43)
        at com.mergebase.log4j.Bytes.streamToBytes(Bytes.java:39)
        at com.mergebase.log4j.Log4JDetector.findLog4jRecursive(Log4JDetector.java:257)
        at com.mergebase.log4j.Log4JDetector.scan(Log4JDetector.java:312)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:337)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:333)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:333)
        at com.mergebase.log4j.Log4JDetector.main(Log4JDetector.java:72)
-- Problem: /dev/hda4 - java.lang.RuntimeException: java.io.FileNotFoundException: /dev/hda4 (No such device or address)
-- Examining /dev/kmsg...
-- Problem /dev/kmsg - java.io.IOException: Invalid argument
-- Problem: /dev/log - java.lang.RuntimeException: java.io.FileNotFoundException: /dev/log (No such device or address)
-- Examining /dev/null...
```
Is the java version crucial? Currently running "openjdk version "1.8.0_275"" on the NAS

**Comment by marcb4** [comment]
> Probably we need to add an "ignore" control (to ignore /dev). On my machine scanning "/dev" does this, but appears that's not the case for you. :-(

an ignore/exclude option would be very useful as it also tried to scan /proc on my systems.

**Comment by juliusmusseau** [comment]
Newest version should be a lot better.  (It now skips files that don't end in *.zip/*.jar/*.ear/*.war/*.aar suffix).

**Comment by Feathered-Serpent** [comment]
New version works great, both on my NAS and on Windows. From my side the case is closed.
