### ISSUE TITLE
Unzip exceptions with 14-12, but 13-12 works

### ISSUE THREAD

**Issue by jsark78** [mergebase/log4j-detector#28]
Hi.

I have unzip exceptions with 14-12 on several machines:

$ java -jar log4j-detector-2021.12.14.jar /opt/tomcat/webapps/awi.war
-- Analyzing paths (could take a long time).
-- Note: specify the '--verbose' flag to have every file examined printed to STDERR.
-- Problem /opt/tomcat/webapps/awi.war!/WEB-INF/bundle/webui-logback.jar!/lib/commons-lang3-3.8.1.jar - java.io.EOFException: Unexpected end of ZLIB input stream
-- Problem /opt/tomcat/webapps/awi.war!/WEB-INF/bundle/webui-logback.jar!/lib/guava-19.0.jar - java.io.EOFException
-- Problem /opt/tomcat/webapps/awi.war!/WEB-INF/bundle/webui-logback.jar!/lib/logback-classic-1.2.3.jar - java.io.EOFException: Unexpected end of ZLIB input stream
-- Problem /opt/tomcat/webapps/awi.war!/WEB-INF/bundle/webui-logback.jar!/lib/logback-core-1.2.3.jar - java.io.EOFException: Unexpected end of ZLIB input stream
-- Problem /opt/tomcat/webapps/awi.war!/WEB-INF/bundle/webui-logback.jar!/lib/slf4j-api-1.7.16.jar - java.io.EOFException
-- Problem /opt/tomcat/webapps/awi.war!/WEB-INF/bundle/com.automic.rest.api.jar!/lib/validation-api.jar - java.io.EOFException: Unexpected end of ZLIB input stream
-- Problem /opt/tomcat/webapps/awi.war!/WEB-INF/bundle/webui-chart.jar!/lib/commons-lang3-3.5.jar - java.io.EOFException: Unexpected end of ZLIB input stream

For instance with:

$ java -version
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)

on

$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: OracleServer
Description:    Oracle Linux Server release 7.9
Release:        7.9
Codename:       n/a

This is NOT a permission issue. Version 13-12 works fine!

p.s. it would be great if previous versions were available in Github, I couldn't locate the old version here or anywhere else on the web, had to source it from a colleague who happened to have it.

p.p.s. even with 13-12, if I do "--verbose", it does not list the class files it (presumably) scans, only the included JAR files. It would be great and very reassuring if it listed the actual files as well. I assume that's how it works, by scanning class files and such?

Thanks, best regards.

**Comment by jsark78** [comment]
Additional note: This problem is also not specific to WAR files. I encountered the same problem on various hosts also when using the tool on JAR files, or paths with JAR files in them.

**Comment by jsark78** [comment]
Also, the tool says "No vulnerable Log4J 2.x samples found in supplied paths: ..." even if there were errors.

Please kindly reconsider this. A tool should NOT say that everything is okay when there were errors (e.g. in my case, it didn't check ANY of the files successfully, but still summarizes that there are no vulnerabilities)! That seems dangerous to me.

**Comment by jsark78** [comment]
Here's the full exception, including call stack.

-- Problem: /opt/tomcat/webapps/awi/WEB-INF/bundle/webui-logback.jar!/lib/logback-core-1.2.3.jar - java.io.EOFException: Unexpected end of ZLIB input stream
java.io.EOFException: Unexpected end of ZLIB input stream
        at java.util.zip.InflaterInputStream.fill(Unknown Source)
        at java.util.zip.InflaterInputStream.read(Unknown Source)
        at java.util.zip.ZipInputStream.read(Unknown Source)
        at java.util.zip.ZipInputStream.closeEntry(Unknown Source)
        at java.util.zip.ZipInputStream.getNextEntry(Unknown Source)
        at com.mergebase.log4j.Log4JDetector.findLog4jRecursive(Log4JDetector.java:205)
        at com.mergebase.log4j.Log4JDetector.findLog4jRecursive(Log4JDetector.java:282)
        at com.mergebase.log4j.Log4JDetector.scan(Log4JDetector.java:439)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:499)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:494)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:494)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:494)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:494)
        at com.mergebase.log4j.Log4JDetector.main(Log4JDetector.java:81)

**Comment by juliusmusseau** [comment]
Fixed in v2021.12.16.

Re:  ". A tool should NOT say that everything is okay when there were errors" - I will create a new ticket to track this idea.

**Comment by juliusmusseau** [comment]
p.s.  I now leave the pre-built binaries (including older versions) in the root folder.

p.p.s.  There is a super-secret "--debug" flag that causes the tool to list every *.class file it examines.

**Comment by jsark78** [comment]
Thanks, this is all very good news. Also many thanks for your work!
