### ISSUE TITLE
Crashes frequently on windows

### ISSUE THREAD

**Issue by jangatzke** [mergebase/log4j-detector#3]
At least on windows systems there seem to be many files that cause errors like this:

Exception in thread "main" java.lang.NullPointerException
        at java.util.Arrays.sort(Arrays.java:1438)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:326)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:328)
        at com.mergebase.log4j.Log4JDetector.main(Log4JDetector.java:69)

This makes it impossible to run a full system scan against c:\.

**Comment by juliusmusseau** [comment]
Fixed.  Look for version v2021.12.13.
