### ISSUE TITLE
Exception on encrypted ZIP entry

### ISSUE THREAD

**Issue by juergen-loh** [mergebase/log4j-detector#6]
Hi,
I got an exception about encrypted ZIP entries (on Windows):

\...\FOO.zip FAILED: java.lang.RuntimeException: java.util.zip.ZipException: encrypted ZIP entry not supported
java.lang.RuntimeException: java.util.zip.ZipException: encrypted ZIP entry not supported
        at com.mergebase.log4j.Log4JDetector$4.getFreshZipStream(Log4JDetector.java:289)
        at com.mergebase.log4j.Log4JDetector.findLog4jRecursive(Log4JDetector.java:112)
        at com.mergebase.log4j.Log4JDetector.scan(Log4JDetector.java:300)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:325)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:321)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:321)
        at com.mergebase.log4j.Log4JDetector.analyze(Log4JDetector.java:321)
        at com.mergebase.log4j.Log4JDetector.main(Log4JDetector.java:69)
Caused by: java.util.zip.ZipException: encrypted ZIP entry not supported
        at java.util.zip.ZipInputStream.readLOC(Unknown Source)
        at java.util.zip.ZipInputStream.getNextEntry(Unknown Source)
        at java.util.jar.JarInputStream.<init>(Unknown Source)
        at java.util.jar.JarInputStream.<init>(Unknown Source)
        at com.mergebase.log4j.Log4JDetector$4.getFreshZipStream(Log4JDetector.java:286)
        ... 7 more

But it looks like the scan continues anyway.

(Great tool, thank you!)

**Comment by juliusmusseau** [comment]
Thanks for the bug report !   I'll see if I can replicate this in my environment to at least make the error message friendlier.

**Comment by juliusmusseau** [comment]
Error message should be friendlier now!

**Comment by juergen-loh** [comment]
Tanks!
